server:
  port: 8080
spring:
  application:
    name: "prueba-quind"
  devtools:
    add-properties: false
  #h2:
   # console:
    #  enabled: true
     # path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://quind.choawwe0ghno.us-east-1.rds.amazonaws.com:5432/postgres"
    username: "root"
    password: "admin123"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
